### ISSUE TITLE
Signing OStree commit never finishing

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-pipeline#178]
I looked at the [current job](https://jenkins-fedora-coreos.apps.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/10835) running and noticed the sign ostree stage has been running for over 13H. The logs show me: 

```
[fedora-coreos-fedora-coreos-pipeline] Running shell script
+ set -xeuo pipefail
+ export AWS_CONFIG_FILE=/.aws-fcos-builds-bot-config/config
+ AWS_CONFIG_FILE=/.aws-fcos-builds-bot-config/config
+ cosa sign robosignatory --s3 fcos-builds/prod/streams/testing-devel/builds --extra-fedmsg-keys stream=testing-devel --ostree --gpgkeypath /etc/pki/rpm-gpg --fedmsg-conf /etc/fedora-messaging-cfg/fedmsg.toml
Successfully started consumer thread
Uploading s3://fcos-builds/prod/streams/testing-devel/builds/tmp/ostree-commit-object
Sending ostree-sign request for build 31.20191220.20.0
Exception in thread CrochetReactor:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/crochet/_eventloop.py", line 412, in <lambda>
    target=lambda: self._reactor.run(installSignalHandlers=False),
  File "/usr/lib64/python3.7/site-packages/twisted/internet/base.py", line 1271, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/lib64/python3.7/site-packages/twisted/internet/base.py", line 1251, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/lib64/python3.7/site-packages/twisted/internet/base.py", line 752, in startRunning
    raise error.ReactorAlreadyRunning()
twisted.internet.error.ReactorAlreadyRunning
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 313, in publish
    eventual_result.wait(timeout=timeout)
  File "/usr/lib/python3.7/site-packages/crochet/_eventloop.py", line 239, in wait
    result = self._result(timeout)
  File "/usr/lib/python3.7/site-packages/crochet/_eventloop.py", line 201, in _result
    raise TimeoutError()
crochet._eventloop.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/coreos-assembler/cmd-sign", line 300, in send_message_impl
    **body
  File "/usr/lib/python3.7/site-packages/fedora_messaging/api.py", line 319, in publish
    raise wrapper
fedora_messaging.exceptions.PublishTimeout: None
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Not sure if there is something for us to do about that. I'm killing this job so others can start and retry this process.

**Comment by jlebon** [comment]
Looking into this.
